version: '3.6'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    container_name: elasticsearch
    ports: ['9200:9200']
    volumes:
      - ./../config/es_data:/usr/share/elasticsearch/data
    environment:
      - node.name=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=ecommerce_sample_cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      stack:
        aliases:
          - elasticsearch

networks: {stack: {}}

# use docker volume to persist ES data outside of a container.
volumes:
  es_data:
    driver: local
